apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: chat-service
      labels:
        app: chat-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
    spec:
      containers:
      - name: chat-service
        image: wm3/chat-service:0.3.46
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: postgres-configs
        - configMapRef:
            name: mongodb-configs
        env: null
        livenessProbe:
          httpGet:
            path: /chat/actuator/health
            port: 8080
          initialDelaySeconds: 500
          periodSeconds: 30
          timeoutSeconds: 60
          failureThreshold: 8
        readinessProbe:
          httpGet:
            path: /chat/actuator/health
            port: 8080
          initialDelaySeconds: 460
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        resources:
          limits:
            cpu: 350m
            memory: 3000Mi
          requests:
            cpu: 160m
            memory: 600Mi
