version: '3.2'

#networks:
#    wm3-network:
#        driver: bridge

services:
    #nginx:
    #    build:
    #        dockerfile: ./kubernetes/nginx/nginx.dockerfile
    #        context: ./docker-apps/kubernetes/nginx/
    #    image: wm3/nginx
    #    container_name: nginx

    mongo:
        image: mongo
        volumes:
            - //c/data/db:/data/db
        container_name: mongo
        
    elasticsearch:
        image: elasticsearch
        container_name: elasticsearch
        
    auth:
        build:
            dockerfile: ./auth.Dockerfile
            context: ./docker-apps/
            args:
                VERSION: 123
        image: wm3/auth-service
        container_name: auth-service
    
    notification:
        build:
            dockerfile: ./notification.Dockerfile
            context: ./docker-apps/
        image: wm3/notification-service
        container_name: notification-service
    
    storage:
        build:
            dockerfile: ./storage.Dockerfile
            context: ./docker-apps/
        image: wm3/storage-service
        container_name: storage-service

    news:
        build:
            dockerfile: ./news.Dockerfile
            context: ./docker-apps/
        image: wm3/news-service
        container_name: news-service
    
    chat:
        build:
            dockerfile: ./chat.Dockerfile
            context: ./docker-apps/
        image: wm3/chat-service
        container_name: chat-service
        
    socket:
        build:
            dockerfile: ./socket.Dockerfile
            context: ./docker-apps/
        image: wm3/socket-service
        container_name: socket-service

    #up:
    #    build:
    #        dockerfile: ../up/Dockerfile
    #        context: ../up/
    #    image: wm3/up-service
    #    container_name: up-service

    demo:
        build:
            dockerfile: ./demo.Dockerfile
            context: ./docker-apps/
        image: wm3/demo-service
        container_name: demo-service

        #ports:
        #    - "8080:8080"
        #networks:
        #    - wm3-network
        #restart: always
        #depends_on:
        #    - "mongo"
        #    - "auth"
        #    - "storage"
        #environment:
        #    MONGODB_URI_PRIMARY: "mongodb://admin:red321Company@mongo:27017/chat?authSource=admin&readPreference=primary"
        #    MONGODB_URI_SECONDARY: "mongodb://admin:red321Company@mongo:27017/auth?authSource=admin&readPreference=primary"
        #    DOMAIN: "https://local.webmodule.com.br"
        #    CLIENT_ID: angular
        #    CLIENT_SECRET: "red_wm3@an6u1@r%"
        #    TOKNEN_INFO_URI: https://local.webmodule.com.br/auth/oauth/check_token
    