apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: wm3/notification-service
        imagePullPolicy: IfNotPresent # <-- change to Always
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: config
        env:
          - name: "MONGODB_URI"
            value: "mongodb://admin:red321Company@mongo:27017/notification?authSource=admin&readPreference=primary"
        resources:
          limits:
            cpu: 200m
            #memory: 4000Mi
          requests:
            cpu: 100m
            #memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
#versions: https://github.com/kubernetes-sigs/metrics-server/
#kubectl apply -f components.yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior: 
    scaleDown: 
      stabilizationWindowSeconds: 300
      policies: 
      - type: Pods
        value: 1
        periodSeconds: 180
