apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: "dpage/pgadmin4"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: pgadmin
        env:
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin
                key: pgadmin-password
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        volumeMounts:
          - name: nfs-storage
            mountPath: /var/lib/pgadmin
            subPath: pgadmin
          - name: pgadmin-config
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
            readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-storage-pvc
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
