apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: storage-service
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: wm3/storage-service:0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-storage
          mountPath: /storage
          subPath: storage
        env:
        - name: DOMAIN
          value: wm3.redcompaby.com.br
        - name: LOCAL_PATH
          value: storage
        - name: STORE_IN_AWS
          value: 'false'
        livenessProbe:
          httpGet:
            path: /storage/actuator/health
            port: 8080
          initialDelaySeconds: 360
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        readinessProbe:
          httpGet:
            path: /storage/actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        resources:
          limits:
            cpu: 150m
            memory: 1300Mi
          requests:
            cpu: 50m
            memory: 200Mi
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-storage-pvc
