apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
        volumeMounts:
        - name: nfs-nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx/nginx.conf
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 400m
            memory: 400Mi
      volumes:
      - name: nfs-nginx
        persistentVolumeClaim:
          claimName: nfs-nginx-pvc
