apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: "1"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
        - name: nfs-nginx
          mountPath: /etc/nginx
          subPath: nginx
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 600Mi
      dnsPolicy: ClusterFirst
      volumes:
      - name: nfs-nginx
        persistentVolumeClaim:
          claimName: nfs-storage-pvc
