apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nginx-pvc
  namespace: nginx
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi