apiVersion: v1
kind: ConfigMap
metadata:
  name: general-configs
data:
  CLIENT_ID: angular
  CLIENT_SECRET: red_wm3@an6u1@r%
  DOMAIN: https://local.webmodule.com.br
  TOKNEN_INFO_URI: https://local.webmodule.com.br/auth/oauth/check_token
  PUSH_NOTIFICATION_URL: http://notification-service
  SOCKET_URL: http://socket-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configs
data:
  FOUNDATION_DATABASE_URL: jdbc:postgresql://postgres:5432/wm3?createDatabaseIfNotExist=true&useSSL=false
  FOUNDATION_DATABASE_USERNAME: admin
  FOUNDATION_DATABASE_PASSWORD: red321Company
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configs
data:
  MONGODB_APP_URI: mongodb://admin:red321Company@mongo:27017/auth?authSource=admin&readPreference=primary&maxIdleTimeMS=36000000
  MONGODB_URI: mongodb://admin:red321Company@mongo:27017/auth?authSource=admin&readPreference=primary&maxIdleTimeMS=36000000
