apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: socket-service
      labels:
        app: socket-service
    spec:
      containers:
      - name: socket-service
        image: wm3/socket-service:0.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: mongodb-configs
        resources:
          limits:
            cpu: 150m
            memory: 800Mi
          requests:
            cpu: 50m
            memory: 150Mi
