apiVersion: v1
kind: Service
metadata:
  name: socket-service
  labels:
    app: socket-service
spec:
  type: NodePort
  selector:
    app: socket-service
  ports:
    - name: http
      port: 30000
      targetPort: 30000
    - name: http-api
      port: 30001
      targetPort: 30001