apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.236 #external-nfs-server
    path: "/var/nfs/k8s"