apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: wm3/notification-service:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: mongodb-configs
        env:
        - name: NOTIFICATION_EXPIRATION_DATE_DAYS
          value: '15'
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 60
          failureThreshold: 8
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        resources:
          limits:
            cpu: 150m
            memory: 800Mi
          requests:
            cpu: 50m
            memory: 150Mi
