apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  #serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:4.2.0-bionic
        #args:
        #  - -repair
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-volume
          mountPath: /mongo/db
        env:
        - name: AUTH
          value: "yes"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "red321Company"
      volumes:
      - name: mongo-volume
        hostPath:
          path: /C/data/db2
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30100
