---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-persistent-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume-persistent
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: slow
  claimRef:
    name: mongo-volume-persistent-claim
  gcePersistentDisk:
    pdName: my-app-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo:4.2.0-bionic
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-persistent-claim
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-mongo

spec:
  type: NodePort # "ClusterIP" para comunicação interna
  selector:
    run: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30100