apiVersion: apps/v1
kind: Deployment
metadata:
  name: up-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: up-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: up-service
      labels:
        app: up-service
    spec:
      containers:
      - name: up-service
        image: wm3/up-service
        imagePullPolicy: IfNotPresent #TODO: Always
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: mongodb-configs
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 360
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi