apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-service
        version: '5.4'
      name: auth-service
    spec:
      containers:
      - name: auth-service
        ports:
        - containerPort: 8080
        image: wm3/auth-service:0.1.2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: postgres-configs
        env:
        - name: CLIENT_ID_API
          value: api
        - name: CLIENT_SECRET_API
          value: api_wm3@p15re8%
        - name: PUBLIC_KEY_FILE
          value: public_key.pem
        - name: PRIVATE_KEYFILE
          value: private_key.pem
        - name: JWT_ISSUER
          value: wm3@redcompany.com.br
        - name: JAVA_OPTS
          value: -server -Dlogging.level.org.springframework=INFO,DEBUG,ERROR -Dlogging.root=INFO,DEBUG,ERROR
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 180
        type: Pods
        value: 1
      stabilizationWindowSeconds: 300
  maxReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
