apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service
    version: '5.1'
  name: auth-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: auth-service
  type: NodePort
