apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: "TCP"
    # Port accessible inside cluster
    port: 8080
    # Port to forward to inside the pod
    targetPort: 8080
    # Port accessible outside cluster
    nodePort: 30010
  