
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata: 
  name: auth-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: auth-service-insgress
spec:
  hosts:
  - "auth.kubernetes.newtech.academy"
  #- "*"
  gateways:
  - auth-gateway
  http:
    route:
    - destination:
        host: auth.default.svc.cluster.local
        port: 
          number: 10000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: auth-hello
spec:
  hosts:
  - "auth.kubernetes.newtech.academy"
  #- "*"
  gateways:
  - auth-gateway
  http:
  - match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: auth.default.svc.cluster.local
        port: 
          number: 10000
  