apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo-service
  ports:
    - name: http 
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30050