---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata: 
  name: applications-ingressgateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http-web
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
        #tls:
      #  mode: SIMPLE # enables HTTPS on this port
      #  credentialName: "httpbin-credential"
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: app-virtual-services
spec:
  hosts:
  - "*"
  gateways:
  - applications-ingressgateway
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: nginx.default.svc.cluster.local
          #subset: v1
          port: 
            number: 80
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /
