---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata: 
  name: applications-ingressgateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http-web
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: app-virtual-services
spec:
  hosts:
  - "*"
  gateways:
  - applications-ingressgateway
  http:
    - match:
      - uri:
          prefix: /auth/
      route:
      - destination:
          host: auth-service #label
          #subset: v1
          port: 
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /

    - match:
      - uri:
          prefix: /chat/
      route:
      - destination:
          host: chat-service #label
          #subset: v1
          port: 
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /chat/

    - match:
      - uri:
          prefix: /news/
      route:
      - destination:

          host: news-service #label
          #subset: v1
          port: 
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /news/
    
    - match:
      - uri:
          prefix: /storage/
      route:
      - destination:
          host: storage-service #label
          #subset: v1
          port: 
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /
    
    - match:
      - uri:
          prefix: /notification/
      route:
      - destination:
          host: notification-service #label
          #subset: v1
          port: 
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /
    
    - match:
      - uri:
          prefix: /socket/
      route:
      - destination:
          host: socket-service #label
          #subset: v1
          port:
            number: 30000
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /
    
    - match:
      - uri:
          prefix: /socket-api/
      route:
      - destination:
          host: socket-service #label
          #subset: v1
          port:
            number: 30001
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /

    - match:
      - uri:
          prefix: /up/
      route:
      - destination:
          host: up-service #label
          #subset: v1
          port:
            number: 8080
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /
    
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: nginx.default.svc.cluster.local
          #subset: v1
          port:
            number: 80
        #weight: 100 # porcentagem de requests que virão para este destino
      rewrite:
        uri: /