---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata: 
  name: mongo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 31018 #15021:31149/TCP,80:32633/TCP,443:32725/TCP,31400:31357/TCP,15443:31507/TCP
        name: mongo-tcp
        protocol: MONGO
      hosts:
        - "*"
---
#kubectl port-forward svc/mongo -n default 27017
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongo-vitual
spec:
  hosts:
  - "*"
  gateways:
  - mongo-gateway
  tcp:
    - match:
        - port: 27017
      route:
        - destination:
            host: mongo
            port:
              number: 27017
