apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
spec:
  selector:
    matchLabels:
      app: news-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      name: news-service
      labels:
        app: news-service
    spec:
      containers:
      - name: news-service
        image: wm3/news-service:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: postgres-configs
        - configMapRef:
            name: mongodb-configs
        env: null
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 50Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: news-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: news-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180
