apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      name: news-service
      labels:
        app: news-service
    spec:
      containers:
      - name: news-service
        image: wm3/news-service:0.3.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: general-configs
        - configMapRef:
            name: postgres-configs
        - configMapRef:
            name: mongodb-configs
        env: null
        livenessProbe:
          httpGet:
            path: /news/actuator/health
            port: 8080
          initialDelaySeconds: 460
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /news/actuator/health
            port: 8080
          initialDelaySeconds: 400
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 10
        resources:
          limits:
            cpu: 300m
            memory: 1400Mi
          requests:
            cpu: 150m
            memory: 400Mi
