#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: news-service
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: news-service
#  minReplicas: 1
#  maxReplicas: 1
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
#  behavior:
#    scaleDown:
#      stabilizationWindowSeconds: 300
#      policies:
#      - type: Pods
#        value: 1
#        periodSeconds: 180
