apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-service
  labels:
    app: storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-service
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      name: storage-service
      labels:
        app: storage-service
        version: '0.1'
    spec:
      containers:
      - name: storage-service
        image: wm3/storage-service
        imagePullPolicy: IfNotPresent #TODO: Always
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: storage-volume
          mountPath: /storage
        env:
          - name: "DOMAIN"
            value: "wm3.redcompaby.com.br"
          - name: "LOCAL_PATH"
            value: "files"
          - name: "STORE_IN_AWS"
            value: "false"
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 50Mi
        livenessProbe: #verificar o health do container
          httpGet:
            path: /actuator/health # ver qual caminha para verificar se esta saudavel
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 60
          failureThreshold: 8
        readinessProbe: #a aplicação estará pronta para receber requisição a partir do momento que receber sucesso no get do path
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 60
          timeoutSeconds: 60
          failureThreshold: 8
      volumes:
      - name: storage-volume
        hostPath:
          path: /home/administrador/projects/storage
          type: DirectoryOrCreate
        #gitRepo:
        #  repository: "git@somewhere:me/my-git-repository.git"
        #  revision: "22f1d8406d464b0c0874075539c1f2e96c253775"
        
#---
#versions: https://github.com/kubernetes-sigs/metrics-server/
#kubectl apply -f components.yaml
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: storage-service
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: storage-service
#  minReplicas: 1
#  maxReplicas: 1
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50
#  behavior: 
#    scaleDown: 
#      stabilizationWindowSeconds: 300
#      policies: 
#      - type: Pods
#        value: 1
#        periodSeconds: 180
